import "./globals.css";
import "./index.scss";
import type { Metadata } from "next";
import { Monda } from "next/font/google";

const monda = Monda({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "ArgensSQL • Bitnine Global Inc.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monda.className}>{children}</body>
    </html>
  );
}
